[build]
  command = "make build"
  functions = "functions"
  publish = "./"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/tommycwu/okta-go-registration-hook"
[[redirects]]
  from = "/registration/*"
  to = "/.netlify/functions/inline/:splat"
  status = 200
